export const PLATFORMS = [
  {
    id: 'youtube',
    name: 'YouTube Shorts',
    emoji: '▶️',
    color: '#FF0000',
    maxSec: 60,
    ratio: '9:16',
    hashtagCount: '3-5',
    tone: '정보성 + 신뢰감',
    tips: '처음 3초 훅 필수. 자막 크게. 설명란에 링크.',
  },
  {
    id: 'instagram',
    name: 'Instagram Reels',
    emoji: '📸',
    color: '#E1306C',
    maxSec: 90,
    ratio: '9:16',
    hashtagCount: '20-30',
    tone: '감성적 + 라이프스타일',
    tips: '트렌디한 음악 필수. 텍스트 오버레이. 스토리 연동.',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    emoji: '🎵',
    color: '#00f2ea',
    maxSec: 60,
    ratio: '9:16',
    hashtagCount: '5-10',
    tone: '재미 + 바이럴',
    tips: '틱톡 트렌드 사운드 활용. 도전 형식. 댓글 유도.',
  },
  {
    id: 'naver_clip',
    name: '네이버 클립',
    emoji: '🟢',
    color: '#03C75A',
    maxSec: 60,
    ratio: '9:16',
    hashtagCount: '5-10',
    tone: '실용적 + 정보',
    tips: '네이버 쇼핑 연동. 상품 태그 활용. 한국 감성.',
  },
  {
    id: 'kakao',
    name: '카카오',
    emoji: '💛',
    color: '#FEE500',
    maxSec: 30,
    ratio: '1:1 or 9:16',
    hashtagCount: '3-5',
    tone: '친근 + 일상',
    tips: '카카오톡 공유 유도. 짧고 강렬하게. 이모티콘 활용.',
  },
  {
    id: 'daangn',
    name: '당근',
    emoji: '🥕',
    color: '#FF6F0F',
    maxSec: 30,
    ratio: '4:3 or 1:1',
    hashtagCount: '3-5',
    tone: '동네 이웃 + 신뢰',
    tips: '지역 기반 언급. 직거래 느낌. 가격 강조.',
  },
  {
    id: 'toss',
    name: '토스',
    emoji: '💸',
    color: '#0064FF',
    maxSec: 15,
    ratio: '1:1',
    hashtagCount: '2-3',
    tone: '깔끔 + 금융/혜택',
    tips: '할인/적립 강조. 숫자 크게. 심플한 구성.',
  },
]

export const CATEGORIES = [
  { id: 'beauty', name: '뷰티', emoji: '💄', searchQuery: '2025 뷰티 신상품 구매후기 베스트' },
  { id: 'fashion', name: '패션', emoji: '👗', searchQuery: '2025 패션 트렌드 인기 상품 후기' },
  { id: 'food', name: '식품', emoji: '🍱', searchQuery: '2025 식품 베스트셀러 후기 인기' },
  { id: 'electronics', name: '전자기기', emoji: '📱', searchQuery: '2025 가성비 전자제품 추천 후기' },
  { id: 'home', name: '생활/인테리어', emoji: '🏠', searchQuery: '2025 생활용품 인테리어 인기 추천' },
  { id: 'baby', name: '육아', emoji: '👶', searchQuery: '2025 육아용품 인기 베스트 후기' },
  { id: 'health', name: '건강/영양', emoji: '💊', searchQuery: '2025 건강식품 영양제 인기 추천' },
  { id: 'pet', name: '반려동물', emoji: '🐾', searchQuery: '2025 반려동물 용품 인기 추천' },
  { id: 'sports', name: '스포츠', emoji: '🏋️', searchQuery: '2025 운동 스포츠용품 인기 후기' },
  { id: 'travel', name: '여행', emoji: '✈️', searchQuery: '2025 여행 용품 인기 추천 후기' },
  { id: 'book', name: '도서/교육', emoji: '📚', searchQuery: '2025 베스트셀러 도서 추천 인기' },
  { id: 'game', name: '게임/취미', emoji: '🎮', searchQuery: '2025 게임 취미 용품 인기 추천' },
]

export const IMAGE_STYLES = [
  { id: 'watercolor', name: '수채화', desc: 'soft watercolor illustration', preview: '🎨' },
  { id: 'minimal', name: '미니멀', desc: 'clean minimal product photography white background', preview: '⬜' },
  { id: '3d', name: '3D 렌더링', desc: 'photorealistic 3D render glossy', preview: '✨' },
  { id: 'lifestyle', name: '라이프스타일', desc: 'lifestyle photography natural light cozy', preview: '🌿' },
  { id: 'neon', name: '네온/사이버', desc: 'neon cyberpunk dark background vibrant colors', preview: '🌃' },
  { id: 'pastel', name: '파스텔', desc: 'pastel colors soft dreamy aesthetic', preview: '🌸' },
  { id: 'luxury', name: '럭셔리', desc: 'luxury premium dark gold elegant', preview: '👑' },
  { id: 'cartoon', name: '카툰/일러스트', desc: 'cute cartoon illustration flat design', preview: '🎭' },
  { id: 'cinematic', name: '시네마틱', desc: 'cinematic dramatic lighting moody', preview: '🎬' },
]

export const OPENROUTER_MODELS = [
  { id: 'openai/gpt-4o', name: 'GPT-4o' },
  { id: 'openai/gpt-4o-mini', name: 'GPT-4o Mini (빠름)' },
  { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet' },
  { id: 'google/gemini-pro-1.5', name: 'Gemini Pro 1.5' },
  { id: 'meta-llama/llama-3.1-70b-instruct', name: 'Llama 3.1 70B' },
]

export const CONVERSION_SIGNALS = [
  '한정수량', '오늘마감', '최저가', '무료배송', '쿠폰', '적립',
  '리뷰', '별점', '재구매', '베스트', '신상', '할인',
]
